### ISSUE TITLE
Error when import diffusion

### ISSUE THREAD

**Issue by tiagofer** [pushtechnology/diffusion-examples#8]
Hi, in 6.9.0 version, i receive the error when import diffusion.

`Traceback (most recent call last):
  File "/Users/academiadosbots/Documents/Trade/william_hill/teste_diffusion.py", line 2, in <module>
    import diffusion
  File "/Users/academiadosbots/Documents/Trade/william_hill/.envw/lib/python3.10/site-packages/diffusion/__init__.py", line 4, in <module>
    from .internal.protocol import SessionId
  File "/Users/academiadosbots/Documents/Trade/william_hill/.envw/lib/python3.10/site-packages/diffusion/internal/protocol/__init__.py", line 22, in <module>
    from .message_types import read_stream, ServiceRequestMessage
  File "/Users/academiadosbots/Documents/Trade/william_hill/.envw/lib/python3.10/site-packages/diffusion/internal/protocol/message_types.py", line 14, in <module>
    from diffusion.internal.session.exception_handler import ErrorReasonException
  File "/Users/academiadosbots/Documents/Trade/william_hill/.envw/lib/python3.10/site-packages/diffusion/internal/session/exception_handler.py", line 17, in <module>
    from diffusion.session.exceptions import (
  File "/Users/academiadosbots/Documents/Trade/william_hill/.envw/lib/python3.10/site-packages/diffusion/session/__init__.py", line 25, in <module>
    from diffusion.session.locks.session_locks import SessionLocks, SessionLock
  File "/Users/academiadosbots/Documents/Trade/william_hill/.envw/lib/python3.10/site-packages/diffusion/session/locks/session_locks.py", line 33, in <module>
    class SessionLocks(object):
  File "/Users/academiadosbots/Documents/Trade/william_hill/.envw/lib/python3.10/site-packages/diffusion/session/locks/session_locks.py", line 131, in SessionLocks
    async def lock(
  File "/Users/academiadosbots/Documents/Trade/william_hill/.envw/lib/python3.10/site-packages/diffusion/internal/utils.py", line 261, in transformer
    validated_main_func = validator(func)
  File "pydantic/decorator.py", line 36, in pydantic.decorator.validate_arguments.validate
  File "pydantic/decorator.py", line 78, in pydantic.decorator.ValidatedFunction.__init__
  File "pydantic/typing.py", line 77, in pydantic.typing.get_all_type_hints
    'AsyncContextManager',
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/typing.py", line 1870, in get_type_hints
    value = _eval_type(value, globalns, localns)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/typing.py", line 327, in _eval_type
    return t._evaluate(globalns, localns, recursive_guard)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/typing.py", line 699, in _evaluate
    self.__forward_value__ = _eval_type(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/typing.py", line 327, in _eval_type
    return t._evaluate(globalns, localns, recursive_guard)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/typing.py", line 694, in _evaluate
    eval(self.__forward_code__, globalns, localns),
  File "<string>", line 1, in <module>
NameError: name 'SessionLock' is not defined. Did you mean: 'SessionLockScope'?
profiling: /Users/jenkins/builds/ppJmC2r-/0/engineering/diffusion-sdk/dependencies/python-core/build/python/build/temp.macosx-10.9-x86_64-cpython-310/CMakeFiles/diffusion_core.dir/src/main/bindings/python/cbor.cpp.gcda: cannot open: No such file or directory
profiling: /Users/jenkins/builds/ppJmC2r-/0/engineering/diffusion-sdk/dependencies/python-core/build/python/build/temp.macosx-10.9-x86_64-cpython-310/CMakeFiles/diffusion_core.dir/src/main/bindings/python/delta.cpp.gcda: cannot open: No such file or directory
profiling: /Users/jenkins/builds/ppJmC2r-/0/engineering/diffusion-sdk/dependencies/python-core/build/python/build/temp.macosx-10.9-x86_64-cpython-310/CMakeFiles/diffusion_core.dir/src/main/bindings/python/main.cpp.gcda: cannot open: No such file or directory
profiling: /Users/jenkins/builds/ppJmC2r-/0/engineering/diffusion-sdk/dependencies/python-core/build/python/build/temp.macosx-10.9-x86_64-cpython-310/CMakeFiles/diffusion_core.dir/src/main/cxx_api/buffer.cpp.gcda: cannot open: No such file or directory
`
Thanks.

**Comment by dimejiogunyoye** [comment]
Hi Tiago, I see you're using Python 3.10. Our Python client currently isn't compatible with this version, due to some breaking changes that were introduced. We will have this addressed in a future patch release.

Can you try with Python 3.8? Thanks
